require("./commands/ama")
require("./commands/discord")
require("./commands/donate")
require("./commands/dotfiles")
require("./commands/playlist")
require("./commands/uses")
require("./redemptions/lights")
